/**
 * 旧图标常量兼容层 —— 仅用于平滑迁移，完成替换后删除。
 * 推荐: `import { I } from '@/icons'` + `<Icon :name="..." />`
 */

export const ICONS_LEGACY = {
  // === 全局 icons/index.ts 旧常量 ===
  ICON_STAR_FILL: 'custom:star-fill',
  ICON_STAR: 'custom:star',
  ICON_COPY: 'ion:copy',
  ICON_ERROR: 'ion:alert-circle',
  ICON_EMPTY: 'ion:cube',
  ICON_PLAYLIST: 'ion:list',
  ICON_CLOSE: 'ion:close',
  ICON_RIGHT: 'ion:chevron-forward',
  ICON_LEFT: 'ion:chevron-back',
  ICON_MENU: 'ion:menu',
  ICON_MOVE: 'ion:folder-open',
  ICON_RENAME: 'ion:text',
  ICON_DOWNLOAD: 'ion:download',
  ICON_DELETE: 'ion:trash',
  ICON_ALL_FILE: 'custom:all-file',
  ICON_CANCEL: 'ion:close-circle',
  ICON_FILE_IMAGE: 'custom:image-file',
  ICON_FILE_FOLDER: 'ion:folder',
  ICON_TOP: 'ion:pin',
  ICON_TOP_SOLID: 'ion:pin',
  ICON_FILE_IMPROVE: 'ion:arrow-up-circle',
  ICON_TOAST_SUCCESS: 'ion:checkmark-circle',
  ICON_TOAST_ERROR: 'ion:alert-circle',
  ICON_TOAST_WARNING: 'ion:warning',
  ICON_TOAST_INFO: 'ion:information-circle',
  ICON_TOAST_CLOSE: 'ion:close',
  ICON_GITHUB: 'ion:logo-github',
  ICON_QA: 'ion:help-circle',
  ICON_SPONSOR: 'ion:cafe',
  ICON_THEME_LIGHT: 'ion:sunny',
  ICON_THEME_DARK: 'ion:moon',
  ICON_THEME_SYSTEM: 'ion:contrast',

  // === XPlayer icons.const.ts 旧常量 ===
  ICON_RESTART: 'ion:refresh',
  ICON_AUTO_LOAD: 'ion:sync',
  ICON_PIP: 'ion:videocam',
  ICON_PIP_EXIT: 'ion:videocam-off',
  ICON_SETTINGS: 'ion:settings-sharp',
  ICON_PASUE: 'ion:pause',
  ICON_PLAY: 'ion:play',
  ICON_PLAYER_CORE: 'ion:code-slash',
  ICON_AUDIO_TRACK: 'ion:musical-notes',
  ICON_LOADING: 'ion:sync',
  ICON_FAST_FORWARD: 'ion:play-forward',
  ICON_FAST_REWIND: 'ion:play-back',
  ICON_TRANSFORM: 'ion:resize',
  ICON_ROTATE_LEFT: 'ion:refresh',
  ICON_ROTATE_RIGHT: 'ion:refresh',
  ICON_ROTATE_NORMAL: 'ion:stop',
  ICON_FLIP_X: 'custom:flip-x',
  ICON_FLIP_Y: 'custom:flip-y',
  ICON_LOCATION_ON: 'ion:locate',
  ICON_ROCKET_LAUNCH: 'ion:refresh',
  ICON_ROTATE: 'ion:refresh',
  ICON_SUBTITLES: 'ion:chatbubbles',
  ICON_SUBTITLES_OFF: 'ion:chatbubbles-outline',
  ICON_TIMER: 'ion:timer',
  ICON_VOLUME_OFF: 'ion:volume-off',
  ICON_VOLUME_MUTE: 'ion:volume-mute',
  ICON_VOLUME_DOWN: 'ion:volume-low',
  ICON_VOLUME_UP: 'ion:volume-high',
  ICON_STATISTICS_INFO: 'ion:analytics',
  ICON_SHORTCUTS: 'ion:keypad',
  ICON_ABOUT: 'ion:information-circle',
  ICON_COLOR_ADJUST: 'ion:color-palette',
  ICON_VIEW: 'ion:eye',
  ICON_OTHER: 'ion:ellipsis-vertical',
  ICON_EXTENSION_FEATURE: 'ion:extension-puzzle',
  ICON_WINDOW: 'ion:desktop',
  ICON_PREV: 'ion:play-skip-back',
  ICON_NEXT: 'ion:play-skip-forward',
  ICON_FULLSCREEN: 'ion:expand',
  ICON_FULLSCREEN_EXIT: 'ion:contract',
  ICON_RESET: 'ion:refresh',
  ICON_EXPORT: 'ion:cloud-upload',
  ICON_IMPORT: 'ion:cloud-download',
  ICON_RESET_ALL: 'ion:refresh-circle',
  ICON_PLAYBACK_RATE: 'ion:speedometer',
  ICON_QUALITY: 'ion:disc',
  ICON_PLUS: 'ion:add',
} as const
