export type * as Entity from './entity'
export type * as MyApi from './myApi/index'
export type * as NormalApi from './normalApi/index'
export type * as ProApi from './proApi/index'
export type * as WebApi from './webApi/index'
